name: krew-release-bot
on:
  release:
    types: [published]
jobs:
  run-krew-release-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update new version in krew-index
      uses: rajatjindal/krew-plugin-release@v0.0.38
      with:
        plugin-name: virt
